github-traffic-aggregator/config/routes.rb
Rails.application.routes.draw do
  get "repos/index"
  get "repos/show"
  get "users/index"
  get "users/show"
  get "users/new"
  get "users/edit"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users
  resources :repos
  resources :repo_data
  

  # namespace :repo_data do
  #       resources :repo_traffic_data_views_biweeklies, only: [ :index ]
  #       resources :repo_traffic_data_views_dailies, only: [ :index ]
  #       resources :repo_traffic_data_clones_biweeklies, only: [ :index ]
  #       resources :repo_traffic_data_clones_dailies, only: [ :index ]
  #       resources :repo_traffic_data_referrers_biweeklies, only: [ :index ]
  #       resources :repo_traffic_data_paths_biweeklies, only: [ :index ]
  # end
end

github-traffic-aggregator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

github-traffic-aggregator/app/models/repo.rb
class Repo < ApplicationRecord
  belongs_to :user
end

github-traffic-aggregator/app/models/repo_data/repo_metadata.rb
module RepoData
  class RepoMetadata < ApplicationRecord
    belongs_to :repo
  end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_clones_biweekly.rb
module RepoData
class RepoTrafficDataClonesBiweekly < ApplicationRecord
  belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_clones_daily.rb
module RepoData
class RepoTrafficDataClonesDaily < ApplicationRecord
  belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_paths_weekly.rb
module RepoData
class RepoTrafficDataPathsWeekly < ApplicationRecord
  belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_referrers_weekly.rb
module RepoData
class RepoTrafficDataReferrersWeekly < ApplicationRecord
  belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_views_biweekly.rb
module RepoData
class RepoTrafficDataViewsBiweekly < ApplicationRecord
    belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_data/repo_traffic_data_views_daily.rb
module RepoData
class RepoTrafficDataViewsDaily < ApplicationRecord
  belongs_to :repo
end
end

github-traffic-aggregator/app/models/repo_traffic_data_clones_biweekly.rb
class RepoTrafficDataClonesBiweekly < ApplicationRecord
  belongs_to :repo
end

github-traffic-aggregator/app/models/repo_traffic_data_clones_daily.rb
class RepoTrafficDataClonesDaily < ApplicationRecord
  belongs_to :repo
end

github-traffic-aggregator/app/models/repo_traffic_data_paths_weekly.rb
class RepoTrafficDataPathsWeekly < ApplicationRecord
  belongs_to :repo
end

github-traffic-aggregator/app/models/repo_traffic_data_referrers_weekly.rb
class RepoTrafficDataReferrersWeekly < ApplicationRecord
  belongs_to :repo
end

github-traffic-aggregator/app/models/repo_traffic_data_views_biweekly.rb
class RepoTrafficDataViewsBiweekly < ApplicationRecord
    belongs_to :repo
end

github-traffic-aggregator/app/models/repo_traffic_data_views_daily.rb
class RepoTrafficDataViewsDaily < ApplicationRecord
  belongs_to :repo
end

github-traffic-aggregator/app/models/user.rb
class User < ApplicationRecord
  # has_secure_password - requires uncommenting '''gem "bcrypt", "~> 3.1.7"''' in Gemfile
  has_many :repos, dependent: :destroy
end

github-traffic-aggregator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

github-traffic-aggregator/app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    # Get all repos
    @repos = Repo.all
  end

  def show
    # get repo id
    @repo = Repo.find(params[:id])

    # set time range #STOPPED HERE
    default_start_time = 

    # get the repo id and time period returned from the form
    if params[:start_date_between]


    else
  
      # Get the repo_data for default time period - previous 14 days
      


      @repo_data_traffic_data_views_daily = RepoData::RepoTrafficDataViewsDaily.find_by({repo: Repo.find(params[:id])})
      @repo_data_traffic_data_views_biweekly = RepoData::RepoTrafficDataViewsBiweekly.find_by({repo: Repo.find(params[:id])})
      @repo_data_traffic_data_clones_daily = RepoData::RepoTrafficDataClonesDaily.find_by({repo: Repo.find(params[:id])})
      @repo_data_traffic_data_clones_biweekly = RepoData::RepoTrafficDataClonesBiweekly.find_by({repo: Repo.find(params[:id])})
      @repo_data_traffic_data_referrers_weekly = RepoData::RepoTrafficDataReferrersWeekly.find_by({repo: Repo.find(params[:id])})
      @repo_data_traffic_data_paths_weekly = RepoData::RepoTrafficDataPathsWeekly.find_by({repo: Repo.find(params[:id])})
    end
  end
end

github-traffic-aggregator/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # Get all users
    @users = User.all
  end

  def show
    # Get the user
    @user = User.find(params[:id])
    @repos = Repo.where(user: @user)  
  end
  

  def new
  end

  def edit
  end
end

github-traffic-aggregator/app/helpers/application_helper.rb
module ApplicationHelper
end

github-traffic-aggregator/app/helpers/repos_helper.rb
module ReposHelper
end

github-traffic-aggregator/app/helpers/users_helper.rb
module UsersHelper
end

github-traffic-aggregator/app/views/repos/index.html.erb
<div>
  <h1 class="text-3xl">Repos</h1>
  <h2 class="text-lg">Only listing those with downloaded data </h2>
  <ul class="list-disc list-inside">
    <% @repos.each do |repo| %>    
      <% has_data = RepoData::RepoTrafficDataViewsDaily.find_by({repo: repo}) %>
      <% if has_data %>
      <li><%= link_to repo.name, repo_path(repo) %></li>
      <%end%>
    <% end %>
  </ul>
</div>

github-traffic-aggregator/app/views/repos/show.html.erb
<script src="https://cdn.jsdelivr.net/gh/alumuko/vanilla-datetimerange-picker@latest/dist/vanilla-datetimerange-picker.js"></script>


<div class="w-full h-full">
   <div class="flex flex-col">
     <!--<input type="text" data-controller="daterangepicker" size="24" style="text-align:center">-->
     <div class="flex justify-center">
        <%= form_with url: repo_path(@repo), method: :get do |form| %>
            <%= form.text_field :start_date_between, data: { controller: "daterangepicker" }, value: params[:start_date_between] %>
            <%= form.submit "Filter by date range", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <% end %>
    </div>

   <h1 class="text-2xl auto mx-auto text-center"> RepoData for <%= @repo.name %> </h1>
    <% repo_view_data = RepoData::RepoTrafficDataViewsDaily.where(repo: @repo) %>
    <% repo_view_counts = repo_view_data.map { |data| [data.timestamp, data.count] } %>

    <%# collect uniques and fill in 0 for any missing dates  %>
    <% repo_view_counts = repo_view_data.map { |data| [data.timestamp.strftime("%Y-%m-%d"), data.count] } %>
    <% start_date = repo_view_data.minimum(:timestamp).to_date %>
    <% end_date = repo_view_data.maximum(:timestamp).to_date %>
    <% all_dates = (start_date..end_date).map { |date| date.strftime("%Y-%m-%d") } %>
    <% repo_view_counts_hash = repo_view_counts.to_h %>
    <% all_dates.each do |date| %>
      <% repo_view_counts_hash[date] ||= 0 %>
    <% end %>
    <% repo_view_counts = repo_view_counts_hash.to_a %>
    <% repo_view_counts = repo_view_counts.sort_by { |date, _| Date.parse(date) } %>

    <% repo_view_uniques = repo_view_data.map { |data| [data.timestamp.strftime("%Y-%m-%d"), data.uniques] } %>
    <% repo_view_uniques_hash = repo_view_uniques.to_h %>
    <% all_dates.each do |date| %>
      <% repo_view_uniques_hash[date] ||= 0 %>
    <% end %>
    <% repo_view_uniques = repo_view_uniques_hash.to_a %>
    <% repo_view_uniques = repo_view_uniques.sort_by { |date, _| Date.parse(date) } %>

    <% combined_view_data = [
    { name: 'Views', data: repo_view_counts.to_h },
    { name: 'Uniques', data: repo_view_uniques.to_h }
    ] %>
    <% repo_clone_data = RepoData::RepoTrafficDataClonesDaily.where(repo: @repo) %>

    <%# collect counts and fill in 0 for any missing dates  %>
    <% repo_clone_counts = repo_clone_data.map { |data| [data.timestamp.strftime("%Y-%m-%d"), data.count] } %>
    <% start_date = repo_clone_data.minimum(:timestamp).to_date %>
    <% end_date = repo_clone_data.maximum(:timestamp).to_date %>
    <% all_dates = (start_date..end_date).map { |date| date.strftime("%Y-%m-%d") } %>
    <% repo_clone_counts_hash = repo_clone_counts.to_h %>
    <% all_dates.each do |date| %>
      <% repo_clone_counts_hash[date] ||= 0 %>
    <% end %>
    <% repo_clone_counts = repo_clone_counts_hash.to_a %>
    <% repo_clone_counts = repo_clone_counts.sort_by { |date, _| Date.parse(date) } %>

    <%# collect uniques and fill in 0 for any missing dates  %>
    <% repo_clone_uniques = repo_clone_data.map { |data| [data.timestamp.strftime("%Y-%m-%d"), data.uniques] } %>
    <% repo_clone_uniques_hash = repo_clone_uniques.to_h %>
    <% all_dates.each do |date| %>
      <% repo_clone_uniques_hash[date] ||= 0 %>
    <% end %>
    <% repo_clone_uniques = repo_clone_uniques_hash.to_a %>
    <% repo_clone_uniques = repo_clone_uniques.sort_by { |date, _| Date.parse(date) } %>
    
    <% combined_clone_data = [
    { name: 'Views', data: repo_clone_counts.to_h },
    { name: 'Uniques', data: repo_clone_uniques.to_h }
    ] %>
    <div class="flex flex-col w-3/4 auto mx-auto">
        <div class="pb-5">
            <%= line_chart combined_view_data, title: "view counts", xtitle: "date", ytitle: "count" %>
        </div>
        <div class="pb-5">
            <%= line_chart combined_clone_data, title: "clone counts", xtitle: "date", ytitle: "count" %>
        </div>
    </div>
</div>
</div>

github-traffic-aggregator/app/views/users/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#edit</h1>
  <p>Find me in app/views/users/edit.html.erb</p>
</div>

github-traffic-aggregator/app/views/users/index.html.erb
<div>
  <h1 class="text-3xl">Users</h1>
  <ul class="list-disc list-inside">
    <% @users.each do |user| %>
      <li> <%= link_to user.username, user_path(user) %></li>
    <% end %>
  </ul>
</div>

github-traffic-aggregator/app/views/users/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#new</h1>
  <p>Find me in app/views/users/new.html.erb</p>
</div>

github-traffic-aggregator/app/views/users/show.html.erb
<div>
  <h1 class="text-3xl">Repos of <%= @user.username %></h1>
  <h2 class="text-lg">Only listing those with downloaded data </h2>
 <table class="table-auto border-collapse border border-gray-200 w-full text-left">
  <thead>
    <tr class="bg-gray-100">
      <th class="border border-gray-300 px-4 py-2">Repository Name</th>
      <th class="border border-gray-300 px-4 py-2">Link</th>
    </tr>
  </thead>
  <tbody>
    <% @repos.each do |repo| %>
      <% has_data = RepoData::RepoTrafficDataViewsDaily.find_by({repo: repo}) %>
      <% if has_data %>
        <tr class="hover:bg-gray-50">
          <td class="border border-gray-300 px-4 py-2"><%= repo.name %></td>
          <td class="border border-gray-300 px-4 py-2"><%= link_to 'View Repository', repo_path(repo), class: "text-blue-500 hover:underline" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

</div>